"""Correct name Reservations to Reservation

Revision ID: 3951d21291a9
Revises: 6d746eccdc66
Create Date: 2026-05-12 23:31:20.321177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 


# revision identifiers, used by Alembic.
revision: str = '3951d21291a9'
down_revision: Union[str, Sequence[str], None] = '6d746eccdc66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guest_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'CONFIRMED', 'CANCELLED', name='reservations_status_enum'), nullable=False),
    sa.ForeignKeyConstraint(['guest_id'], ['guest.id'], name=op.f('fk_reservation_guest_id_guest')),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], name=op.f('fk_reservation_location_id_location')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reservation'))
    )
    op.drop_table('reservations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('guest_id', sa.INTEGER(), nullable=False),
    sa.Column('location_id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=9), nullable=False),
    sa.ForeignKeyConstraint(['guest_id'], ['guest.id'], name=op.f('fk_reservations_guest_id_guest')),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], name=op.f('fk_reservations_location_id_location')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reservations'))
    )
    op.drop_table('reservation')
    # ### end Alembic commands ###
