"""Setup relations between guest and location

Revision ID: 3f33e2cf6b38
Revises: 02a389c3ac64
Create Date: 2026-05-06 15:28:17.101938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 


# revision identifiers, used by Alembic.
revision: str = '3f33e2cf6b38'
down_revision: Union[str, Sequence[str], None] = '02a389c3ac64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_guest_location_id_location'), 'location', ['location_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_guest_location_id_location'), type_='foreignkey')
        batch_op.drop_column('location_id')

    # ### end Alembic commands ###
