"""Move many-to-many guest/locations relationships to Reservations table

Revision ID: 6d746eccdc66
Revises: ec719c5fd496
Create Date: 2026-05-12 23:24:23.121934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 


# revision identifiers, used by Alembic.
revision: str = '6d746eccdc66'
down_revision: Union[str, Sequence[str], None] = 'ec719c5fd496'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guest_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'CONFIRMED', 'CANCELLED', name='reservations_status_enum'), nullable=False),
    sa.ForeignKeyConstraint(['guest_id'], ['guest.id'], name=op.f('fk_reservations_guest_id_guest')),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], name=op.f('fk_reservations_location_id_location')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reservations'))
    )
    op.drop_table('guestlocation')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guestlocation',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('guest_id', sa.INTEGER(), nullable=False),
    sa.Column('location_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['guest_id'], ['guest.id'], name=op.f('fk_guestlocation_guest_id_guest')),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], name=op.f('fk_guestlocation_location_id_location')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guestlocation'))
    )
    op.drop_table('reservations')
    # ### end Alembic commands ###
