"""Change Guest many-to-many Locations relationship

Revision ID: ec719c5fd496
Revises: 3f33e2cf6b38
Create Date: 2026-05-12 22:53:03.994378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 


# revision identifiers, used by Alembic.
revision: str = 'ec719c5fd496'
down_revision: Union[str, Sequence[str], None] = '3f33e2cf6b38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guestlocation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guest_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['guest_id'], ['guest.id'], name=op.f('fk_guestlocation_guest_id_guest')),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], name=op.f('fk_guestlocation_location_id_location')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guestlocation'))
    )
    with op.batch_alter_table('guest', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_guest_location_id_location'), type_='foreignkey')
        batch_op.drop_column('location_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_guest_location_id_location'), 'location', ['location_id'], ['id'])

    op.drop_table('guestlocation')
    # ### end Alembic commands ###
